sonar.projectKey=JeronimoGg_Proyecto_CICD
sonar.organization=jeronimogg
sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml
sonar.exclusions=**/__pycache__/**,**/venv/**,**/node_modules/**
sonar.coverage.exclusions=**/tests/**,**/venv/**
sonar.python.version=3.11
